/**
 * Typed wrappers around the Tauri IPC surface.
 *
 * The frontend NEVER talks to external services directly — it only invokes
 * Rust commands (Tauri Core) and subscribes to Rust-emitted events. This module
 * is the single place where `invoke` is called, so the command contract stays
 * in one spot.
 */
import { invoke } from '@tauri-apps/api/core';

/** Body returned by the Python sidecar's `GET /health`. */
export interface SidecarHealth {
  status: string;
  service: string;
  /** ISO-8601 timestamp generated by the sidecar (UTC). */
  time: string;
}

/** Result of a frontend → Rust → sidecar → frontend round-trip. */
export interface PingResult {
  reachable: boolean;
  http_status: number;
  port: number;
  round_trip_ms: number;
  /** Rust-side timestamp of when the check ran (freshness, UTC ISO-8601). */
  checked_at: string;
  health: SidecarHealth | null;
  error: string | null;
}

// --- US Market view -------------------------------------------------------

export interface SourceMeta {
  source: string;
  last_fetched_at: string | null;
  status: string; // "ok" | "error" | "unavailable" | "never"
  detail: string | null;
}

export interface IndexQuote {
  code: string;
  value: number | null;
  change_pct: number | null;
  ts: string | null;
}

export interface SectorQuote {
  sector: string;
  ret: number | null; // fraction (0.012 = 1.2%)
  rel_strength: number | null; // fraction
  date: string | null;
}

export interface BreadthQuote {
  date: string | null;
  index: string;
  advancers: number | null;
  decliners: number | null;
  new_highs: number | null;
  new_lows: number | null;
  pct_above_200dma: number | null; // fraction
  universe: number | null;
}

export interface MetricPoint {
  value: number;
  date: string;
  series_id: string;
}

export interface RatesSnapshot {
  us2y: MetricPoint | null;
  us10y: MetricPoint | null;
  twos10s: MetricPoint | null;
  hy_oas: MetricPoint | null;
  dxy: MetricPoint | null;
  vix: MetricPoint | null;
}

export interface CotQuote {
  market: string;
  date: string | null;
  noncomm_net: number | null;
  noncomm_net_prev: number | null;
  noncomm_long: number | null;
  noncomm_short: number | null;
}

export interface UsMarket {
  indices: IndexQuote[];
  sectors: SectorQuote[];
  breadth: BreadthQuote | null;
  rates: RatesSnapshot;
  cot: CotQuote[];
  freshness: SourceMeta[];
}

export interface RefreshOutcome {
  source: string;
  status: string;
  rows: number;
  detail: string | null;
}

export interface RefreshSummary {
  outcomes: RefreshOutcome[];
  at: string;
}

// --- Composite (Home) -----------------------------------------------------

export interface CompositeComponent {
  name: string;
  label: string;
  weight: number; // effective (renormalized) weight
  raw_weight: number;
  n: number | null; // normalized [-1,1], sign applied
  contribution: number;
  available: boolean;
  note: string | null;
}

export interface CompositeResult {
  ts: string;
  score: number; // 0-100
  regime_key: string;
  regime_label: string;
  components: CompositeComponent[];
  coverage: number; // fraction of weight available
  notes: string[];
}

/** Compute + read the market-regime composite. */
export function getComposite(): Promise<CompositeResult> {
  return invoke<CompositeResult>('get_composite');
}

/** Read the US Market view payload from Rust (reads from DuckDB). */
export function getUsMarket(): Promise<UsMarket> {
  return invoke<UsMarket>('get_us_market');
}

// --- Japan Market view -----------------------------------------------------

export interface FxQuote {
  pair: string;
  rate: number | null;
  change_pct: number | null;
  ts: string | null;
}

export interface FuturesGap {
  futures_code: string;
  futures_value: number | null;
  futures_ts: string | null;
  spot_code: string;
  spot_prev_close: number | null;
  gap_pct: number | null;
}

export interface InvestorFlowQuote {
  week_ending: string;
  investor_type: string;
  market: string;
  net: number | null;
  buy: number | null;
  sell: number | null;
}

export interface ShortSellingQuote {
  date: string;
  market: string;
  short_ratio: number | null;
}

export interface MarginQuote {
  symbol_or_market: string;
  week_ending: string;
  long_balance: number | null;
  short_balance: number | null;
  ratio: number | null;
}

export interface JpMarket {
  indices: IndexQuote[];
  fx: FxQuote[];
  futures_gap: FuturesGap | null;
  investor_flows: InvestorFlowQuote[];
  short_selling: ShortSellingQuote[];
  margin: MarginQuote[];
  jquants_available: boolean;
  freshness: SourceMeta[];
}

export interface WatchItem {
  symbol: string;
  label: string;
  market: string;
}

export function getJpMarket(): Promise<JpMarket> {
  return invoke<JpMarket>('get_jp_market');
}

export function getWatchlist(): Promise<WatchItem[]> {
  return invoke<WatchItem[]>('get_watchlist');
}

export function setWatchlist(items: WatchItem[]): Promise<void> {
  return invoke<void>('set_watchlist', { items });
}

// --- Disclosures / News / Calendar / Alerts / Brief (Session 4) ------------

export interface NewsItem {
  id: string;
  source: string;
  datetime: string;
  title: string;
  url: string;
  summary: string | null;
  summarized_tier: string | null;
  tickers: string[];
}

export interface DisclosureItem {
  id: string;
  source: string;
  company_code: string | null;
  datetime: string;
  doc_type: string | null;
  title: string;
  url: string | null;
  summary: string | null;
  summarized_tier: string | null;
}

export interface CalendarEvent {
  id: string;
  type: string;
  datetime_jst: string;
  country: string;
  importance: string;
  title: string;
  actual: string | null;
  forecast: string | null;
  previous: string | null;
}

export interface Alert {
  id: string;
  ts: string;
  severity: string;
  title: string;
  triggers: string[];
  status: string;
}

export interface AlertRule {
  id: string;
  name: string;
  enabled: boolean;
  condition: string;
}

export interface Brief {
  text: string;
  tier: string;
  generated_at: string;
}

export interface FeedFilter {
  kind?: string;
  source?: string;
  limit?: number;
}

export function getNews(limit?: number): Promise<NewsItem[]> {
  return invoke<NewsItem[]>('get_news', { limit: limit ?? null });
}

export function getDisclosures(filter?: FeedFilter): Promise<DisclosureItem[]> {
  return invoke<DisclosureItem[]>('get_disclosures', { filter: filter ?? null });
}

export function getCalendar(limit?: number): Promise<CalendarEvent[]> {
  return invoke<CalendarEvent[]>('get_calendar', { limit: limit ?? null });
}

export function getAlerts(limit?: number): Promise<Alert[]> {
  return invoke<Alert[]>('get_alerts', { limit: limit ?? null });
}

export function getAlertRules(): Promise<AlertRule[]> {
  return invoke<AlertRule[]>('get_alert_rules');
}

export function getBrief(): Promise<Brief> {
  return invoke<Brief>('get_brief');
}

// --- Cross-market / Settings / Credentials (Session 5) ---------------------

export interface CrossTransmission {
  driver: string;
  path: string;
  effect_note: string;
}

export interface MetricLabel {
  label: string;
  value: number | null;
}

export interface CrossMarket {
  transmissions: CrossTransmission[];
  metrics: MetricLabel[];
  freshness: SourceMeta[];
}

export interface SettingKV {
  key: string;
  value: string;
}

export interface CredentialStatus {
  source: string;
  configured: boolean;
}

export function getCrossMarket(): Promise<CrossMarket> {
  return invoke<CrossMarket>('get_cross_market');
}

export function getSettings(): Promise<SettingKV[]> {
  return invoke<SettingKV[]>('get_settings');
}

export function setSetting(key: string, value: string): Promise<void> {
  return invoke<void>('set_setting', { key, value });
}

export function setCredential(source: string, token: string): Promise<void> {
  return invoke<void>('set_credential', { source, token });
}

export function getCredentialStatus(): Promise<CredentialStatus[]> {
  return invoke<CredentialStatus[]>('get_credential_status');
}

export interface AiStatus {
  mode: string;
  provider: string; // "local" | "claude" | "rule"
  label: string;
  detail: string | null;
  local_available: boolean;
  local_endpoint: string | null;
  local_model: string | null;
  claude_available: boolean;
}

export function getAiStatus(): Promise<AiStatus> {
  return invoke<AiStatus>('get_ai_status');
}

/** Per-source last-fetched time + status. */
export function getFreshness(): Promise<SourceMeta[]> {
  return invoke<SourceMeta[]>('get_freshness');
}

/** Manually refresh one source, or all US sources when omitted. */
export function refresh(source?: string): Promise<RefreshSummary> {
  return invoke<RefreshSummary>('refresh', { source: source ?? null });
}

/** Status of the local databases owned by Rust. */
export interface DbStatus {
  duckdb_path: string;
  sqlite_path: string;
  duckdb_exists: boolean;
  sqlite_exists: boolean;
  /** Rust-side timestamp of initialization (UTC ISO-8601). */
  initialized_at: string;
}

/**
 * Ping the sidecar through Rust. Runs the full IPC chain:
 * frontend `invoke` → Rust command → sidecar `GET /health` → result.
 */
export function pingSidecar(): Promise<PingResult> {
  return invoke<PingResult>('ping_sidecar');
}

/** Report the paths and existence of the DuckDB / SQLite files. */
export function getDbStatus(): Promise<DbStatus> {
  return invoke<DbStatus>('get_db_status');
}

/** True when running inside the Tauri webview (vs. a plain browser dev server). */
export function isTauri(): boolean {
  return typeof window !== 'undefined' && '__TAURI_INTERNALS__' in window;
}
